spring:
  application:
    name: clients
  datasource:
    url: jdbc:postgresql://localhost:5432/clients
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate.ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: never

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server.port: 8080
